title: BH Wiki
description: BananaHackers Wiki hosted on GitHub Pages
theme: just-the-docs

url: https://minhduc-bui1.github.io/wiki
baseurl: "/docs"

aux_links:
  Discord: https://discord.gg/rQ93zEu
  Matrix: https://matrix.to/#/%23bananahackers:mozilla.org
  Reddit: https://reddit.com/r/KaiOS
  Google Groups: https://groups.google.com/g/bananahackers
