title: KaiOS Wiki
description: BananaHackers Wiki hosted on GitHub Pages
theme: just-the-docs
color_scheme: bananahackers

url: https://dcmnhb.github.io/wiki
logo: "/assets/banana.png"

aux_links:
  BananaHackers Store: https://store.bananahackers.net
  Reddit: https://reddit.com/r/KaiOS
  Discord: https://discord.gg/rQ93zEu

aux_links_new_tab: true

nav_external_links:
  - title: Back to BananaHackers Wiki
    url: https://wiki.bananahackers.net

back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: true
last_edit_time_format: "%B %e, %Y"

gh_edit_link: true
gh_edit_link_text: "Edit this entry on GitHub"
gh_edit_repository: "https://github.com/minhduc-bui1/wiki"
gh_edit_branch: "main"
gh_edit_source: _docs
gh_edit_view_mode: "tree"

callouts:
  warning:
    title: Warning
    color: yellow
  caution:
    title: Caution
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green