title: BananaHackers Wiki
description: BananaHackers Wiki hosted on GitHub Pages
theme: just-the-docs
color_scheme: bananahackers

url: https://minhduc-bui1.github.io/wiki
logo: "/assets/bHackersStore.png"

aux_links:
  BananaHackers Store: https://store.bananahackers.net
  GitHub: https://github.com/minhduc-bui1/wiki

nav_external_links:
  - title: r/KaiOS on Reddit
    url: https://reddit.com/r/KaiOS
  - title: Join our Discord chat
    url: https://discord.gg/rQ93zEu

callouts:
  warning:
    title: Warning
    color: yellow
  caution:
    title: Caution
    color: red
  note:
    title: Note
    color: blue
  success:
    color: green